language: swift
osx_image: xcode11.4
all_branches: true
script:
  - xcodebuild test -workspace FramesIos.xcworkspace -scheme FramesIos -destination 'OS=13.4.1,name=iPhone 11'
after_success:
  - bash <(curl -s https://codecov.io/bash)
deploy:
  provider: script
  script: chmod +x ./scripts/push.sh && ./scripts/push.sh
  skip_cleanup: true
  on:
    tags: true
